Revert "Add keepalive job."
Good for nothing:

> Error: Missing download info for gautamkrishnar/keepalive-workflow@v2

This reverts commit 220d03a2b571010d3db7e4e8405e9fc1f2d55fa3.